version: "3.7"

services:
  backend:
    build: ./backend
    working_dir: /backend
    container_name: backend
    command: python3 dev-entry.py
    volumes:
      - ./backend/:/backend
    depends_on:
      - unknown_mongo
    env_file:
      - .env
  frontend:
    build: ./frontend
    container_name: frontend
    working_dir: /frontend
    command: pnpm docker-dev
    volumes:
      - ./frontend/.svelte-kit/:/frontend/.svelte-kit/
      - ./frontend/patches/:/frontend/patches/
      - ./frontend/scripts/:/frontend/scripts/
      - ./frontend/src/:/frontend/src/
      - ./frontend/static/:/frontend/static/
      - ./frontend/package.json:/frontend/package.json
      - ./frontend/postcss.config.js:/frontend/postcss.config.js
      - ./frontend/svelte.config.js:/frontend/svelte.config.js
      - ./frontend/tailwind.config.js:/frontend/tailwind.config.js
      - ./frontend/vite.config.ts:/frontend/vite.config.ts
    env_file:
      - .env
    environment:
      - PUBLIC_IS_DOCKER=true
  unknown_mongo:
    image: mongo:4.4
    container_name: unknown_mongo
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "./data:/data/db"
  client:
    image: nginx
    ports:
      - 2080:80
    volumes:
      - type: bind
        source: ./dev-proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - frontend
      - backend
