/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/login/google": {
    /** Google Login */
    get: operations["google_login_api_v1_auth_login_google_get"];
  };
  "/api/v1/auth/user_info": {
    /** User Info */
    get: operations["user_info_api_v1_auth_user_info_get"];
  };
  "/api/v1/auth/google": {
    /** Google Auth */
    get: operations["google_auth_api_v1_auth_google_get"];
  };
  "/api/v1/auth/logout": {
    /** Logout */
    get: operations["logout_api_v1_auth_logout_get"];
  };
  "/api/v1/users/": {
    /** Get Users */
    get: operations["get_users_api_v1_users__get"];
    /** Create User */
    post: operations["create_user_api_v1_users__post"];
  };
  "/api/v1/users/{user_data}": {
    /** Delete users by email */
    delete: operations["delete_user_cv_api_v1_users__user_data__delete"];
  };
  "/api/v1/cvs/": {
    /** Create new CV for users */
    post: operations["create_cv_api_v1_cvs__post"];
  };
  "/api/v1/cvs/random_cv": {
    /** Return random users CV */
    get: operations["get_random_cv_api_v1_cvs_random_cv_get"];
  };
  "/api/v1/cvs/{cv_id}": {
    /** Return users CV by ID */
    get: operations["get_user_cv_api_v1_cvs__cv_id__get"];
    /** Delete users CV by ID */
    delete: operations["delete_user_cv_api_v1_cvs__cv_id__delete"];
  };
  "/api/v1/cv_note/": {
    /** Add new HR note to the CV */
    post: operations["add_new_note_api_v1_cv_note__post"];
  };
  "/api/v1/cv_note/{cv_id}": {
    /** Returns all HR notes on the specified CV */
    get: operations["get_cv_notes_api_v1_cv_note__cv_id__get"];
    /** Delete all HR notes to the CV */
    delete: operations["delete_cv_notes_api_v1_cv_note__cv_id__delete"];
  };
  "/api/v1/vacancies/": {
    /** Create new company vacancy */
    post: operations["create_vacancy_api_v1_vacancies__post"];
  };
  "/api/v1/vacancies/random_vacancy": {
    /** Return random company vacancy */
    get: operations["get_random_vacancy_api_v1_vacancies_random_vacancy_get"];
  };
  "/api/v1/vacancies/{vacancy_id}": {
    /** Return company vacancy by ID */
    get: operations["get_company_vacancy_api_v1_vacancies__vacancy_id__get"];
    /** Delete company vacancy by ID */
    delete: operations["delete_company_vacancy_api_v1_vacancies__vacancy_id__delete"];
  };
  "/api/v1/vacancy_note/": {
    /** Add New Note */
    post: operations["add_new_note_api_v1_vacancy_note__post"];
  };
  "/api/v1/vacancy_note/{vacancy_id}/": {
    /** Get Vacancy Notes */
    get: operations["get_vacancy_notes_api_v1_vacancy_note__vacancy_id___get"];
    /** Delete Vacancy Notes */
    delete: operations["delete_vacancy_notes_api_v1_vacancy_note__vacancy_id___delete"];
  };
  "/api/v1/collections/grade": {
    /** Return the collection of existing grades in DB */
    get: operations["get_grades_api_v1_collections_grade_get"];
  };
  "/api/v1/collections/title": {
    /** Return the collection of existing title in DB */
    get: operations["get_titles_api_v1_collections_title_get"];
  };
  "/api/v1/professions/": {
    /** Get All Professions */
    get: operations["get_all_professions_api_v1_professions__get"];
    /** Post Profession */
    post: operations["post_profession_api_v1_professions__post"];
  };
  "/api/v1/skills/": {
    /** Get All Skills */
    get: operations["get_all_skills_api_v1_skills__get"];
    /** Post Skill */
    post: operations["post_skill_api_v1_skills__post"];
  };
  "/api/ping": {
    /** Ping */
    get: operations["ping_api_ping_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** BaseNoteSchema */
    BaseNoteSchema: {
      /**
       * Content Type
       * @default text
       */
      content_type: string;
      /** Note Text */
      note_text: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** CVNoteRequestSchema */
    CVNoteRequestSchema: {
      /**
       * Related Id
       * Format: uuid
       */
      related_id: string;
      /** Note Text */
      note_text: string;
    };
    /** CVNoteResponseSchema */
    CVNoteResponseSchema: {
      /**
       * Related Id
       * Format: uuid
       */
      related_id: string;
      /** Notes */
      notes: components["schemas"]["Note"][];
    };
    /** CVRequestSchema */
    CVRequestSchema: {
      title: components["schemas"]["Title"];
      salary: components["schemas"]["Salary-Input"] | null;
      grade: components["schemas"]["Grade"];
      profession: components["schemas"]["Profession-Input"];
      /** Skillset */
      skillset: string;
    };
    /** CVResponseSchema */
    CVResponseSchema: {
      /**
       * Custom Id
       * Format: uuid
       */
      custom_id: string;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      title: components["schemas"]["Title"];
      salary: components["schemas"]["Salary-Output"] | null;
      grade: components["schemas"]["Grade"];
      profession: components["schemas"]["Profession-Output"];
      /** Skillset */
      skillset: string;
    };
    /**
     * Grade
     * @enum {string}
     */
    Grade: "junior" | "middle" | "senior" | "lead" | "principal";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Note */
    Note: {
      /**
       * Content Type
       * @default text
       */
      content_type: string;
      /** Note Text */
      note_text: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** Profession */
    "Profession-Input": {
      /**
       * Id
       * @description MongoDB document ObjectID
       */
      _id?: string | null;
      /** Name */
      name: string;
    };
    /** Profession */
    "Profession-Output": {
      /**
       * Id
       * @description MongoDB document ObjectID
       */
      _id: string | null;
      /** Name */
      name: string;
    };
    /** ProfessionSchema */
    ProfessionSchema: {
      /** Name */
      name: string;
    };
    /** Salary */
    "Salary-Input": {
      /** Min Level */
      min_level?: number | null;
      /** Max Level */
      max_level?: number | null;
      /**
       * Currency
       * @default USD
       */
      currency?: string;
    };
    /** Salary */
    "Salary-Output": {
      /** Min Level */
      min_level: number | null;
      /** Max Level */
      max_level: number | null;
      /**
       * Currency
       * @default USD
       */
      currency: string;
    };
    /** SkillSchema */
    SkillSchema: {
      /** Name */
      name: string;
    };
    /**
     * Title
     * @enum {string}
     */
    Title: "member" | "lead" | "teamlead" | "manager" | "director";
    /** UserEmailSchema */
    UserEmailSchema: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** UserRequestSchema */
    UserRequestSchema: {
      /** Name */
      name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** UserResponseSchema */
    UserResponseSchema: {
      /**
       * Custom Id
       * Format: uuid
       */
      custom_id: string;
      /** Name */
      name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** VacancyNoteRequestSchema */
    VacancyNoteRequestSchema: {
      /**
       * Related Id
       * Format: uuid
       */
      related_id: string;
      /** Note Text */
      note_text: string;
    };
    /** VacancyNoteResponseSchema */
    VacancyNoteResponseSchema: {
      /**
       * Related Id
       * Format: uuid
       */
      related_id: string;
      /** Notes */
      notes: components["schemas"]["Note"][];
    };
    /** VacancyRequestSchema */
    VacancyRequestSchema: {
      title: components["schemas"]["Title"];
      salary: components["schemas"]["Salary-Input"] | null;
      grade: components["schemas"]["Grade"];
      profession: components["schemas"]["Profession-Input"];
      /** Skillset */
      skillset: string;
    };
    /** VacancyResponseSchema */
    VacancyResponseSchema: {
      /**
       * Custom Id
       * Format: uuid
       */
      custom_id: string;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      title: components["schemas"]["Title"];
      salary: components["schemas"]["Salary-Output"] | null;
      grade: components["schemas"]["Grade"];
      profession: components["schemas"]["Profession-Output"];
      /** Skillset */
      skillset: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Google Login */
  google_login_api_v1_auth_login_google_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** User Info */
  user_info_api_v1_auth_user_info_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserEmailSchema"];
        };
      };
    };
  };
  /** Google Auth */
  google_auth_api_v1_auth_google_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Logout */
  logout_api_v1_auth_logout_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Get Users */
  get_users_api_v1_users__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponseSchema"][];
        };
      };
    };
  };
  /** Create User */
  create_user_api_v1_users__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRequestSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete users by email */
  delete_user_cv_api_v1_users__user_data__delete: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserEmailSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create new CV for users */
  create_cv_api_v1_cvs__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CVRequestSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CVResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Return random users CV */
  get_random_cv_api_v1_cvs_random_cv_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CVResponseSchema"];
        };
      };
    };
  };
  /** Return users CV by ID */
  get_user_cv_api_v1_cvs__cv_id__get: {
    parameters: {
      path: {
        cv_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CVResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete users CV by ID */
  delete_user_cv_api_v1_cvs__cv_id__delete: {
    parameters: {
      path: {
        cv_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Add new HR note to the CV */
  add_new_note_api_v1_cv_note__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CVNoteRequestSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BaseNoteSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Returns all HR notes on the specified CV */
  get_cv_notes_api_v1_cv_note__cv_id__get: {
    parameters: {
      path: {
        cv_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CVNoteResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete all HR notes to the CV */
  delete_cv_notes_api_v1_cv_note__cv_id__delete: {
    parameters: {
      path: {
        cv_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create new company vacancy */
  create_vacancy_api_v1_vacancies__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VacancyRequestSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VacancyResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Return random company vacancy */
  get_random_vacancy_api_v1_vacancies_random_vacancy_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VacancyResponseSchema"];
        };
      };
    };
  };
  /** Return company vacancy by ID */
  get_company_vacancy_api_v1_vacancies__vacancy_id__get: {
    parameters: {
      path: {
        vacancy_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VacancyResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete company vacancy by ID */
  delete_company_vacancy_api_v1_vacancies__vacancy_id__delete: {
    parameters: {
      path: {
        vacancy_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Add New Note */
  add_new_note_api_v1_vacancy_note__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VacancyNoteRequestSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BaseNoteSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Vacancy Notes */
  get_vacancy_notes_api_v1_vacancy_note__vacancy_id___get: {
    parameters: {
      path: {
        vacancy_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VacancyNoteResponseSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Vacancy Notes */
  delete_vacancy_notes_api_v1_vacancy_note__vacancy_id___delete: {
    parameters: {
      path: {
        vacancy_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Return the collection of existing grades in DB */
  get_grades_api_v1_collections_grade_get: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Grade"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Return the collection of existing title in DB */
  get_titles_api_v1_collections_title_get: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Title"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get All Professions */
  get_all_professions_api_v1_professions__get: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProfessionSchema"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Profession */
  post_profession_api_v1_professions__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfessionSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProfessionSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get All Skills */
  get_all_skills_api_v1_skills__get: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SkillSchema"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Skill */
  post_skill_api_v1_skills__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SkillSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SkillSchema"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Ping */
  ping_api_ping_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
